// =====================================================================
//  TODOS LOS TEXTOS DE LA APP, EN UN SOLO SITIO.
//  Para traducirla a otro idioma, se copia este archivo y se traducen los
//  textos. Lo que va entre llaves ({asistente}, {academia}, {n}...) lo
//  rellena la app: no se traduce.
// =====================================================================

export const es = {
  comun: {
    cargando: "Cargando…",
    guardar: "Guardar",
    guardado: "Guardado",
    cancelar: "Cancelar",
    cerrar: "Cerrar",
    volver: "Volver",
    borrar: "Borrar",
    renombrar: "Renombrar",
    reintentar: "Reintentar",
    siguiente: "Siguiente",
    anterior: "Anterior",
    si: "Sí",
    no: "No",
    enviar: "Enviar",
    buscar: "Buscar",
    acciones: "Más acciones",
    confirmarBorrar: "¿Seguro? Se borra de verdad y no se puede recuperar.",
    soloLectura: "Estás en modo soporte: solo lectura. No se puede cambiar nada.",
    errorGenerico: "Algo ha fallado. Vuelve a intentarlo en un momento.",
    demasiadasPeticiones: "Vas muy deprisa. Espera un minuto y vuelve a probar.",
    sinConexion: "Sin conexión. Tu mensaje se enviará al volver.",
    noEncontrado: "No encontrado",
    noEncontradoTexto: "Esto no existe o no tienes permiso para verlo.",
    irAlInicio: "Ir al inicio",
    tema: "Tema {n}",
    pagina: "página {n}",
    articulo: "art. {n}",
    hoy: "hoy",
    ayer: "ayer",
    ia: "IA",
  },

  marca: {
    aviso: "{asistente} es un asistente con inteligencia artificial. Comprueba siempre la cita.",
  },

  chat: {
    placeholder: "Pregúntale a {asistente}…",
    tuPregunta: "Tu pregunta",
    enviar: "Enviar",
    quedan: "Te quedan {n} preguntas hoy",
    quedaUna: "Te queda 1 pregunta hoy",
    modos: { resolver: "Resolver dudas", guiado: "Aprendizaje guiado", examinador: "Examinador" },
    modoAyuda: {
      resolver: "Te contesto directo, con la cita.",
      guiado: "Te llevo con preguntas hasta que llegues tú.",
      examinador: "Te pregunto yo, para que recuerdes.",
    },
    modoGrupo: "Modo del chat",
    saludo: "Hola, {nombre}.",
    saludoSinNombre: "Hola.",
    presentacion: "Soy {asistente}. Pregúntame cualquier duda del temario de {oposicion} y te contesto siempre con el tema y la página.",
    pruebaCon: "Prueba con",
    sugerenciaMemoria: "La última vez te costó {asunto}. ¿Lo repasamos?",
    sugerenciaBoton: "Repasar {asunto}",
    nueva: "Nueva conversación",
    conversaciones: "Mis conversaciones",
    tituloNueva: "Nueva conversación",
    noEstaCabeza: "No está en el temario",
    noEstaTexto: "Eso no aparece en el temario de tu academia, así que no te lo puedo contestar con seguridad. ¿Quieres que se lo pase a tu formador? Verá tu pregunta, pero no tu nombre.",
    noEstaSinOferta: "Eso no aparece en el temario de tu academia, así que no te lo puedo contestar con seguridad.",
    enviadaFormador: "Enviada a tu formador. Te avisamos cuando conteste.",
    noEnviada: "Vale, no se lo pasamos.",
    respuestaFormador: "Respuesta de tu formador",
    meSirvio: "Me sirvió",
    noMeSirvio: "No me sirvió",
    avisarError: "Avisar de un error",
    errorAvisado: "Aviso enviado a tu formador",
    avisarErrorTitulo: "¿Qué está mal en esta respuesta?",
    avisarErrorAyuda: "Tu formador lo revisará. Verá la respuesta, pero no tu nombre.",
    avisarErrorEnviar: "Enviar aviso",
    falloIA: "{asistente} no ha podido contestar ahora. Vuelve a intentarlo: no se ha gastado ninguna pregunta.",
    cortada: "La respuesta se ha cortado. No se ha gastado ninguna pregunta.",
    sinConexion: "Sin conexión. Tu mensaje se enviará al volver.",
    escribiendo: "{asistente} está escribiendo…",
    limiteTitulo: "Por hoy, ya está",
    limiteAlumno: "Has usado tus {n} preguntas de hoy. Mañana a las 00:00 vuelves a tener {n}. Mientras, puedes repasar tus tarjetas o hacer un test de los que ya tienes.",
    limiteAcademia: "Tu academia ha usado todas las preguntas de este mes. Vuelve a haberlas {cuando}. Mientras, puedes repasar tus tarjetas o hacer un test de los que ya tienes.",
    repasarTarjetas: "Repasar mis tarjetas",
    irATests: "Ir a mis tests",
    demasiadoLargo: "La pregunta es demasiado larga. Resúmela un poco.",
  },
  primeraVez: {
    tituloPrivacidad: "Antes de empezar",
    queVe: "Lo que ve tu academia",
    queVeTexto: "Cuándo entras y datos de todos los alumnos sumados, sin nombres.",
    queNoVe: "Lo que no ve nunca",
    queNoVeTexto: "Lo que preguntas, tus notas de test ni lo que {asistente} sabe de ti.",
    ia: "Vas a hablar con una inteligencia artificial",
    iaTexto: "{asistente} es un asistente con inteligencia artificial. Contesta solo con el temario de tu academia y te dice de qué tema y página sale cada respuesta. Aun así puede equivocarse: comprueba siempre la cita.",
    borrar: "Lo que {asistente} apunta de ti lo puedes leer, corregir y borrar cuando quieras en «Lo que sé de ti».",
    edad: "Tengo {edad} años o más, o tengo permiso de mis padres para usar esta app.",
    legal: "Aviso de privacidad y condiciones de uso",
    entendido: "Entendido",
    faltaEdad: "Marca la casilla para seguir.",
    paso: "Paso {n} de {total}",
    atras: "Atrás",
    siguiente: "Siguiente",
    empezar: "Empezar",
    p1: "¿Cómo quieres que te llame?",
    p1Ayuda: "Es lo único de ti que le llega a {asistente}. Ni tu nombre completo ni tu correo.",
    p1Ejemplo: "Por ejemplo: Lucía",
    p2: "¿Qué oposición preparas?",
    p2Ayuda: "Viene marcada la de tu grupo. Solo confírmala.",
    p3: "¿Es tu primera vez o repites?",
    p3a: "Es mi primera vez",
    p3b: "Repito",
    p4: "¿Cuántas horas estudias al día?",
    horas: { "menos-2": "Menos de 2 horas", "2-4": "De 2 a 4 horas", "4-6": "De 4 a 6 horas", "mas-6": "Más de 6 horas" },
    p5: "¿Qué te cuesta más?",
    dificultad: {
      arrancar: "Arrancar a estudiar",
      memorizar: "Memorizar leyes",
      entender: "Entender textos técnicos",
      nervios: "Los nervios del examen",
    },
    faltaRespuesta: "Elige una opción para seguir.",
    faltaNombre: "Escribe cómo quieres que te llame.",
  },

  visor: {
    titulo: "Visor del temario",
    resaltado: "lo usado en la respuesta está resaltado",
    paginaDe: "{n} de {total}",
    pagina: "Página {n}",
    anterior: "Página {n}",
    siguiente: "Página {n}",
    cerrar: "Cerrar el visor",
    demasiadas: "Has visto muchas páginas en poco tiempo. Vuelve en un rato: el temario se lee aquí página a página y no se puede descargar.",
    noDisponible: "Esta página no está disponible.",
    indice: "Esta página es del índice del tema.",
  },

  conversaciones: {
    titulo: "Mis conversaciones",
    buscar: "Buscar en tus conversaciones",
    vacio: "Aún no tienes conversaciones",
    vacioTexto: "Tu primera pregunta aparecerá aquí.",
    preguntar: "Preguntar",
    renombrar: "Renombrar",
    borrar: "Borrar",
    borrarConfirmar: "¿Borrar esta conversación? Se borra de verdad y no se puede recuperar.",
    nuevoNombre: "Nuevo nombre",
    sinResultados: "No hay conversaciones con «{q}».",
    mensajes: "{n} mensajes",
  },

  crear: {
    titulo: "Crear material",
    subtitulo: "Elige qué quieres estudiar y cómo. Todo lo que crees se guarda solo en tu biblioteca.",
    paso: "Paso {n}",
    pasoDe: "Paso {n} de 3 · {que}",
    temas: "Temas",
    temasAyuda: "Hasta 3",
    eligeTemas: "Elige los temas",
    formato: "Formato",
    formatoAyuda: "Uno por material",
    eligeFormato: "Elige el formato",
    opciones: "Opciones",
    ajusta: "Ajusta tu material",
    estiloResumen: "Estilo del resumen",
    estiloAyuda: "Puedes volver a generarlo si no te convence",
    temaPaginas: "Tema {n} · {p} páginas",
    maxTemas: "Como mucho 3 temas por material.",
    faltaTema: "Elige al menos un tema.",
    siguienteFormato: "Siguiente: elegir formato",
    siguienteOpciones: "Siguiente: opciones",
    cambiar: "Cambiar",
    formatos: {
      resumen: ["Resumen", "En esquema, Cornell o ejecutivo"],
      esquema: ["Esquema", "Mapa en árbol, de lo general a lo concreto"],
      presentacion: ["Presentación", "De 10 a 20 diapositivas"],
      tarjetas: ["Tarjetas de repaso", "De 20 a 60, con modo literal"],
      test: ["Test de práctica", "10, 20, 30 o 50 preguntas"],
      simulacro: ["Simulacro", "Con reloj y penalización"],
    },
    estilos: {
      esquema: ["En esquema", "Puntos y subpuntos. Lo que hay que memorizar, en negrita."],
      cornell: ["Cornell", "Preguntas clave a la izquierda, notas a la derecha y un resumen abajo."],
      ejecutivo: ["Ejecutivo", "Una página de texto corto, por apartados."],
    },
    diapositivas: "Número de diapositivas",
    tarjetas: "Número de tarjetas",
    modoLiteral: "Modo literal",
    modoLiteralAyuda: "Solo artículos, plazos, fechas y leyes, con el dato exacto bien grande.",
    preguntas: "Número de preguntas",
    dificultad: "Dificultad",
    dificultades: { facil: "Fácil", medio: "Medio", oposicion: "Nivel oposición" },
    simulacroRegla: "Tiempo: {min} minutos ({seg} s por pregunta). Cada fallo resta {resta}. Las preguntas en blanco no restan.",
    boton: "Crear",
    botonTarjetas: "Crear {n} tarjetas",
    quedan: "Te quedan {n} materiales este mes",
    quedaUno: "Te queda 1 material este mes",
    limiteAlumno: "Has usado tus {n} materiales de este mes. Vuelves a tenerlos {cuando}. Mientras, puedes repasar lo que ya tienes en tu biblioteca.",
    limiteAcademia: "Tu academia ha usado todos los materiales de este mes. Vuelve a haberlos {cuando}.",
    sinTemario: "Tu academia aún no ha subido el temario. En cuanto lo suba, podrás crear material.",
    resumenEleccion: "{formato} · {temas}",
  },
  material: {
    creandoTitulo: "Creando tu material…",
    puedesSalir: "Puedes salir: te lo guardamos en tu biblioteca.",
    leyendo: "Leyendo el temario",
    buscando: "Buscando lo importante",
    errorTitulo: "No se ha podido crear",
    errorTexto: "Ha fallado al crearlo. No se ha gastado ningún material.",
    insuficiente: "Este tema no da para este formato",
    descargar: "Descargar PDF",
    renombrar: "Renombrar",
    mover: "Mover a carpeta",
    sinCarpeta: "Sin carpeta",
    regenerar: "Volver a generar",
    regenerarConfirmar: "Volver a generar cuenta como un material más. ¿Seguimos?",
    borrar: "Borrar",
    borrarConfirmar: "¿Borrar este material? Se borra de verdad y no se puede recuperar.",
    actualizado: "Temario actualizado",
    actualizadoTexto: "Este material se hizo con una versión anterior del temario.",
    volverACrear: "Volver a crear",
    deMiAcademia: "De tu academia",
    compartidoPor: "Lo ha compartido tu formador",
    sirvio: "¿Te ha servido?",
    empezarTest: "Empezar el test",
    empezarSimulacro: "Empezar el simulacro",
    intentos: "Tus intentos",
    sinIntentos: "Aún no lo has hecho.",
    repasarTarjetas: "Repasar estas tarjetas",
    tocaGirar: "Toca para girar",
    preguntaN: "Pregunta · {n} de {total}",
    respuesta: "Respuesta",
    literal: "Modo literal",
    zonaPreguntas: "Preguntas clave",
    zonaNotas: "Notas",
    zonaResumen: "Resumen",
    diapositiva: "Diapositiva {n} de {total}",
    preguntasN: "{n} preguntas",
    tarjetasN: "{n} tarjetas",
  },
  biblioteca: {
    titulo: "Biblioteca",
    buscar: "Buscar en tu biblioteca",
    pestanas: { resumenes: "Resúmenes", esquemas: "Esquemas", presentaciones: "Presentaciones", tarjetas: "Tarjetas", tests: "Tests", academia: "De mi academia" },
    carpetas: "Carpetas",
    todo: "Todo",
    nuevaCarpeta: "Nueva carpeta",
    nombreCarpeta: "Nombre de la carpeta",
    renombrarCarpeta: "Renombrar carpeta",
    borrarCarpeta: "Borrar carpeta",
    borrarCarpetaConfirmar: "¿Borrar la carpeta? El material que tiene dentro no se borra: pasa a «Todo».",
    filtrarTema: "Filtrar por tema",
    columnas: { material: "Material", tipo: "Tipo", tema: "Tema", creado: "Creado" },
    vacio: "Tu biblioteca está vacía",
    vacioTexto: "Todo lo que crees se guarda aquí solo.",
    crearPrimero: "Crear mi primer material",
    academiaVacio: "Tu formador aún no ha compartido material",
    academiaVacioTexto: "Cuando lo haga, aparecerá aquí. Mientras, puedes crear el tuyo.",
    crearMaterial: "Crear material",
    sinResultados: "No hay material con esos filtros.",
    creando: "Creando…",
    fallo: "No se ha podido crear",
  },
  test: {
    salir: "Salir del test",
    salirConfirmar: "¿Salir? Perderás las respuestas de este intento.",
    deTotal: "{n} de {total}",
    respondidas: "{n} respondidas",
    enBlancoN: "{n} en blanco",
    anterior: "Anterior",
    siguiente: "Siguiente",
    terminar: "Terminar",
    dejarEnBlanco: "Dejar en blanco",
    reglaSimulacro: "Cada fallo resta {resta}. Las preguntas en blanco no restan.",
    tiempoAgotado: "Se ha acabado el tiempo.",
    terminarConfirmar: "Tienes {n} preguntas sin contestar. ¿Terminar igualmente?",
    resultado: "Resultado",
    volverBiblioteca: "Volver a la biblioteca",
    conPenalizacion: "con penalización",
    sinPenalizacion: "sin penalización",
    sobre10: "sobre 10",
    aciertos: "aciertos",
    fallos: "fallos",
    enBlanco: "en blanco",
    repasarFallos: "Repasar mis fallos",
    notaPrivada: "Esta nota solo la ves tú.",
    correccion: "Corrección",
    todas: "Todas",
    falladas: "Falladas · {n}",
    blancas: "En blanco · {n}",
    pregunta: "Pregunta {n}",
    fallada: "Fallada",
    acertada: "Acertada",
    blanca: "En blanco",
    tuRespuesta: "Tu respuesta:",
    correcta: "Correcta:",
    sinFallos: "No has fallado ninguna. ¡Muy bien!",
  },
  repasar: {
    titulo: "Repasar hoy",
    subtitulo: "Lo que te toca hoy: tus tarjetas y las preguntas que fallaste.",
    tarjetasHoy: "{n} tarjetas para hoy",
    preguntasHoy: "{n} preguntas falladas",
    la_sabia: "La sabía",
    no_la_sabia: "No la sabía",
    vacio: "Hoy no tienes nada que repasar",
    vacioTexto: "Crea tarjetas o haz un test y aquí aparecerá lo que te toca.",
    crearTarjetas: "Crear tarjetas",
    terminado: "¡Hecho por hoy!",
    terminadoTexto: "Has repasado {n}. Mañana te tocan {m}.",
    noCuenta: "Repasar no gasta preguntas ni materiales.",
    comprobar: "Comprobar",
    bien: "¡Bien! Esa ya la sabes.",
    mal: "Esta vuelve mañana.",
    siguiente: "Siguiente",
    preguntaFallada: "Pregunta que fallaste",
  },
  progreso: {
    titulo: "Mi progreso",
    racha: "Días seguidos estudiando",
    tests: "Tests hechos",
    notaMedia: "Nota media",
    grafica: "Tus notas",
    graficaVacia: "Haz tu primer test y aquí verás cómo avanzas.",
    flojos: "Temas flojos",
    fuertes: "Temas fuertes",
    sinDatos: "Aún no hay datos suficientes.",
    soloTu: "Todo esto solo lo ves tú. Ni tu formador ni tu academia.",
    aciertosTema: "{pct} % de aciertos",
  },

  loQueSe: {
    titulo: "Lo que sé de ti",
    subtitulo: "Esto es lo que {asistente} tiene apuntado para ayudarte mejor. Puedes corregirlo o borrarlo cuando quieras: se borra de verdad.",
    perfil: "Tu perfil",
    comoLlamar: "Cómo quieres que te llame",
    repite: "¿Repites?",
    horas: "Horas de estudio al día",
    dificultad: "Lo que más te cuesta",
    notas: "Lo que he ido apuntando",
    vacio: "Iré apuntando lo que te cuesta y lo que dominas a medida que estudiemos.",
    corregir: "Corregir",
    borrar: "Borrar",
    borrarTodo: "Borrar todo",
    borrarTodoConfirmar: "¿Borrar todas las notas? Solo se queda tu perfil. No se puede deshacer.",
    borrada: "Borrado.",
    tipos: { cuesta: "Le cuesta", domina: "Domina", fallo_test: "En los tests", preferencia: "Prefiere" },
    guardarPerfil: "Guardar el perfil",
    perfilGuardado: "Perfil guardado. {asistente} lo usará desde tu próxima pregunta.",
    si: "Sí, repito",
    no: "No, es mi primera vez",
  },
  cuenta: {
    titulo: "Mi cuenta",
    avisos: "Avisos por correo",
    recordatorio: "Recordatorio si llevo {dias} días sin entrar",
    respuestas: "Aviso cuando mi formador conteste una duda",
    apariencia: "Apariencia",
    temas: { auto: "Como el móvil", oscuro: "Oscuro", claro: "Claro" },
    misDatos: "Mis datos",
    descargarBiblioteca: "Descargar toda mi biblioteca",
    descargarBibliotecaAyuda: "Un PDF con todo tu material.",
    copiaDatos: "Pedir una copia de mis datos",
    copiaDatosAyuda: "Un archivo con todo lo que guardamos de ti. Se genera al momento.",
    borrarDatos: "Borrar mis datos",
    borrarDatosAyuda: "Borra al momento tus conversaciones, tu material, tus tests y lo que {asistente} sabe de ti. Tu cuenta sigue abierta y empezarás de cero.",
    borrarDatosConfirmar: "¿Borrar todos tus datos? Se borran de verdad y al momento. No se puede deshacer.",
    borrarDatosEscribe: "Escribe BORRAR para confirmar",
    borrarDatosBoton: "Borrar todos mis datos",
    ayuda: "¿Necesitas ayuda?",
    ayudaTexto: "Escribe a tu academia:",
    legal: "Aviso de privacidad y condiciones de uso",
    loQueSe: "Lo que sé de ti",
    salir: "Cerrar sesión",
    guardado: "Guardado",
  },
  legal: {
    titulo: "Aviso de privacidad y condiciones de uso",
    plantilla: "Plantilla pendiente de revisión por un abogado.",
  },

  temario: {
    titulo: "Temario",
    subtitulo: "Los PDF de cada tema. {asistente} contesta solo con lo que hay aquí.",
    subir: "Subir tema",
    sustituir: "Sustituir",
    ver: "Ver",
    historial: "Historial",
    notas: "Notas del formador",
    nota: "Nota del formador",
    vacio: "Aún no hay temario",
    vacioTexto: "Sube el PDF del primer tema para que el asistente pueda empezar a contestar.",
    avisoSinTemario: "El asistente no contestará hasta que haya temario.",
    columnas: { tema: "Tema", paginas: "Páginas", version: "Versión", actualizado: "Actualizado", por: "Subido por", estado: "Estado" },
    estados: { subiendo: "Subiendo…", procesando: "Procesando {pct} %", lista: "Listo", error: "Error", sustituida: "Sustituida" },
    version: "v{n}",
    total: "{n} páginas de {max} en toda la academia",
    subirTitulo: "Subir o sustituir tema",
    oposicion: "Oposición",
    queTema: "¿Qué tema es?",
    temaNuevo: "Un tema nuevo",
    temaExistente: "Sustituir el tema {n} · {nombre}",
    numero: "Número del tema",
    nombre: "Nombre del tema",
    nombreEjemplo: "Por ejemplo: Ley 39/2015, del Procedimiento Administrativo Común",
    nombreCorto: "Nombre corto (para las citas)",
    nombreCortoEjemplo: "Por ejemplo: Ley 39/2015",
    archivo: "El PDF del tema",
    arrastra: "Arrastra aquí el PDF o pulsa para elegirlo",
    soloPdf: "Solo PDF con texto, hasta {mb} MB.",
    elegirOtro: "Elegir otro",
    empezar: "Subir y procesar",
    leyendo: "Leyendo el PDF… página {n} de {total}",
    subiendoArchivo: "Guardando el PDF…",
    guardandoPaginas: "Guardando las páginas… {n} de {total}",
    procesando: "Preparando la búsqueda. Puedes salir: te avisamos por correo al terminar.",
    listo: "¡Listo! {asistente} ya usa este tema.",
    escaneado: "Este PDF parece escaneado y el asistente no podrá leerlo. Súbelo en versión con texto.",
    grande: "El PDF pesa más de {mb} MB. Divídelo en dos temas o comprímelo.",
    noPdf: "Ese archivo no es un PDF.",
    faltanDatos: "Completa el número y el nombre del tema.",
    mientras: "Mientras se procesa, el asistente sigue usando la versión anterior.",
    versiones: "Versiones",
    sinNotas: "Aún no hay notas del formador en este tema. Se crean al contestar una duda con «Guardar como nota del formador».",
    editar: "Editar",
    retirar: "Retirar",
    retirada: "Retirada",
    retirarConfirmar: "¿Retirar esta nota? El asistente dejará de usarla.",
    volverTemario: "Temario",
  },
  alumnos: {
    titulo: "Alumnos",
    invitar: "Invitar alumnos",
    columnas: { nombre: "Nombre", correo: "Correo", grupo: "Grupo", acceso: "Último acceso", invitacion: "Invitación" },
    aceptada: "Aceptada",
    pendiente: "Pendiente",
    baja: "De baja",
    nunca: "Nunca",
    haceDias: "hace {n} días",
    hoy: "hoy",
    ayer: "ayer",
    todos: "Todos",
    cambiarGrupo: "Cambiar de grupo",
    reenviar: "Reenviar invitación",
    reenviada: "Invitación reenviada.",
    darDeBaja: "Dar de baja",
    bajaConfirmar: "¿Dar de baja a {nombre}? Dejará de poder entrar. Sus datos se borran a los 30 días.",
    reactivar: "Volver a dar de alta",
    vacio: "Aún no hay alumnos",
    vacioTexto: "Invítalos uno a uno o sube una lista.",
    plantilla: "Descargar la plantilla de lista",
    noVe: "Aquí no se ve qué pregunta cada alumno, ni sus notas, ni su memoria. Nunca.",
    invitarTitulo: "Invitar alumnos",
    uno: "Uno a uno",
    lista: "Con una lista",
    nombre: "Nombre y apellidos",
    correo: "Correo",
    grupo: "Grupo",
    enviar: "Enviar invitación",
    enviada: "Invitación enviada a {correo}.",
    subirLista: "Sube la lista (Excel o CSV con las columnas Nombre, Correo y Grupo)",
    vistaPrevia: "Vista previa",
    filasBien: "{n} alumnos listos para invitar",
    filasMal: "Hay errores en {n} filas: corrígelas en tu hoja y vuelve a subirla. No se invita a nadie hasta que estén bien.",
    enviarLista: "Invitar a {n} alumnos",
    enviadas: "Se han enviado {n} invitaciones.",
    errores: {
      nombre: "Falta el nombre",
      correo: "Correo mal escrito",
      grupo: "El grupo «{grupo}» no existe o no es tuyo",
      repetido: "Correo repetido en la lista",
      yaExiste: "Ya está dado de alta",
    },
    vacioLista: "La lista está vacía o no tiene las columnas Nombre, Correo y Grupo.",
    ilegible: "No se ha podido leer el archivo. Súbelo en Excel (.xlsx) o CSV.",
    sinGrupos: "Aún no tienes grupos. Pide a la dirección de la academia que te asigne uno.",
    compartida: "Posible cuenta compartida",
  },
  materialClase: {
    titulo: "Material para clase",
    subtitulo: "Crea material igual que tus alumnos y compártelo con tus grupos. Les aparece en «De mi academia».",
    crear: "Crear material para clase",
    compartidoCon: "Compartido con",
    compartir: "Compartir con",
    dejarDeCompartir: "Dejar de compartir",
    noCompartido: "Sin compartir",
    vacio: "Aún no has compartido material",
    vacioTexto: "Lo que compartas aparecerá a tus alumnos en «De mi academia».",
    guardarCompartir: "Guardar",
    compartidoOk: "Guardado.",
  },
  dudas: {
    titulo: "Dudas",
    subtitulo: "Lo que tus alumnos no han podido resolver con {asistente}. Nunca verás quién lo pregunta.",
    pestanas: { sin_respuesta: "Sin respuesta", error: "Errores avisados", no_sirvio: "No le sirvió" },
    pendientes: "{n} pendientes",
    vacio: "No hay dudas pendientes",
    vacioTexto: "Cuando el asistente no sepa algo o un alumno avise de un error, aparecerá aquí.",
    pregunta: "Pregunta",
    respuestaAsistente: "Respuesta del asistente",
    comentario: "Comentario del alumno",
    sinRespuestaAsistente: "(No estaba en el temario.)",
    grupo: "Grupo",
    tema: "Tema",
    sinTema: "Sin tema",
    contestar: "Contestar",
    tuRespuesta: "Tu respuesta",
    tuRespuestaAyuda: "Le llegará al alumno en su conversación como «Respuesta de tu formador».",
    guardarNota: "Guardar como nota del formador en este tema",
    guardarNotaAyuda: "El asistente la usará y la citará cuando otro alumno pregunte lo mismo.",
    eligeTema: "Elige el tema",
    enviar: "Enviar respuesta",
    resuelta: "Marcar como resuelta",
    resueltaAyuda: "Sin contestar (por ejemplo, un error que no era error).",
    contestada: "Contestada",
    marcadaResuelta: "Resuelta",
    verTodas: "Ver también las contestadas",
    volver: "Dudas",
    respondidaPor: "Contestada por {nombre} · {fecha}",
  },
  ayuda: {
    titulo: "Ayuda",
    faq: "Preguntas frecuentes",
    escribenos: "Escríbenos",
    escribenosTexto: "Te contestamos en menos de 24 horas laborables (de lunes a viernes, de 9:00 a 18:00).",
    mensaje: "Tu mensaje",
    enviar: "Enviar",
    enviado: "Mensaje enviado. Te contestaremos por correo.",
    preguntas: [
      ["¿Por qué el asistente dice que algo no está en el temario?", "Porque solo contesta con el temario que habéis subido. Si falta algo, el alumno puede pasarte la duda y tú contestarla; si la guardas como nota del formador, el asistente la usará a partir de entonces."],
      ["¿Cuánto tarda en procesarse un PDF?", "Unos minutos. Mientras tanto el asistente sigue usando la versión anterior, y te llega un correo al terminar."],
      ["¿Puedo ver lo que pregunta un alumno?", "No. Ni el formador ni la dirección ven lo que pregunta un alumno concreto, sus notas ni su memoria. Es lo que hace que se atrevan a preguntar. Veréis los datos sumados en Métricas."],
      ["Un alumno no recibe el enlace para entrar", "Que mire en la carpeta de correo no deseado. Puedes reenviarle la invitación desde Alumnos. Si sigue sin llegar, escríbenos."],
      ["¿Qué pasa si subo un PDF escaneado?", "No se puede leer: el asistente necesita PDF con texto. Pide a quien lo hizo la versión digital."],
    ],
  },
  metricas: {
    periodo: "Periodo",
    dias: "{n} días",
    oposicion: "Oposición",
    grupo: "Grupo",
    formador: "Formador",
    todos: "Todos",
    todas: "Todas",
    exportar: "Exportar a Excel",
    pocos: "No hay suficientes alumnos para mostrar este dato sin identificar a nadie.",
    faltan: "Faltan alumnos para mostrar este dato sin identificar a nadie.",
    alcanceFormador: "Solo tus grupos",
    alcanceDueno: "Toda la academia",
    uso: {
      titulo: "Uso",
      activos: "Alumnos activos",
      preguntas: "Preguntas",
      materiales: "Materiales creados",
      horas: "A qué horas estudian",
      horasAyuda: "Preguntas por día de la semana y hora. Más oscuro, más preguntas.",
      vacio: "Aún no hay actividad. Los datos aparecerán en cuanto tus alumnos empiecen a usar a {asistente}.",
    },
    dudas: {
      titulo: "Dudas y atascos",
      frecuentes: "Dudas más frecuentes",
      frecuentesAyuda: "Agrupadas por asunto. Nunca se enseña la frase de un alumno.",
      asunto: "{n} dudas de {m} alumnos",
      atascos: "Dónde se atascan",
      atascosAyuda: "Temas con más dudas y más fallos en los tests, de peor a mejor.",
      falta: "Lo que falta en el temario",
      faltaAyuda: "Lo que el asistente no supo responder, por asunto.",
      dudasTema: "{n} dudas",
      fallosTema: "{pct} % de fallos en tests",
      vacio: "Aún no hay dudas en este periodo.",
      preparando: "Agrupando las dudas…",
    },
    riesgo: {
      titulo: "Alumnos en riesgo",
      subtitulo: "Los que llevan {n} días o más sin entrar. Es el único dato con nombre: solo quién entra y cuándo.",
      dias: "{n} días sin entrar",
      nunca: "Nunca ha entrado",
      vacio: "Ningún alumno lleva más de {n} días sin entrar.",
      columnas: { nombre: "Nombre", grupo: "Grupo", dias: "Días sin entrar", correo: "Correo" },
    },
    progreso: {
      titulo: "Progreso del grupo",
      subtitulo: "Siempre sumado, nunca por alumno.",
      notaMedia: "Nota media de los tests",
      tests: "{n} tests",
      fuertes: "Temas fuertes",
      flojos: "Temas flojos",
      vacio: "Aún no hay tests suficientes para mostrar el progreso del grupo.",
    },
    material: {
      titulo: "Material",
      masCreados: "Formatos más creados",
      peorValorados: "Peor valorados",
      creados: "{n} creados",
      valoracion: "{pct} % «no me sirvió» de {n} valoraciones",
      vacio: "Aún no se ha creado material.",
      sinValoraciones: "Aún no hay valoraciones.",
    },
  },
  ajustes: {
    equipo: {
      titulo: "Equipo",
      subtitulo: "Los formadores de la academia y los grupos que lleva cada uno.",
      invitar: "Invitar formador",
      nombre: "Nombre y apellidos",
      correo: "Correo",
      grupos: "Grupos que lleva",
      sinGrupos: "Sin grupos",
      quitar: "Quitar del equipo",
      quitarConfirmar: "¿Quitar a {nombre} del equipo? Dejará de poder entrar.",
      yoFormador: "Yo también soy formador",
      yoFormadorAyuda: "Para subir temario, contestar dudas y ver tu parte de formador.",
      guardar: "Guardar",
      vacio: "Invita a tus formadores para que suban el temario y den de alta a los alumnos.",
      invitado: "Invitación enviada.",
      tu: "Tú",
    },
    grupos: {
      titulo: "Oposiciones y grupos",
      subtitulo: "Las oposiciones de la academia, con su regla de simulacro, y sus grupos.",
      regla: "Regla del simulacro",
      resta: "Cada fallo resta",
      segundos: "Segundos por pregunta",
      guardarRegla: "Guardar la regla",
      restas: { "0": "Nada", "0.25": "Un cuarto", "0.3333": "Un tercio", "0.5": "La mitad" },
      nuevoGrupo: "Crear grupo",
      nombreGrupo: "Nombre del grupo",
      renombrar: "Renombrar",
      archivar: "Archivar",
      archivado: "Archivado",
      desarchivar: "Recuperar",
      archivarConfirmar: "¿Archivar el grupo {nombre}? Sus alumnos siguen, pero no se podrá invitar a nadie más.",
      alumnos: "{n} alumnos",
      formadores: "Formadores: {nombres}",
      sinFormadores: "Sin formador",
      vacio: "Crea tu primer grupo",
      nuevaOposicion: "Para añadir una oposición nueva, escríbenos desde Ayuda: implica subir su temario y montarla.",
    },
    consumo: {
      titulo: "Consumo",
      subtitulo: "Lo usado este mes frente al tope de la academia.",
      preguntas: "Preguntas del mes",
      materiales: "Materiales del mes",
      alumnos: "Alumnos",
      al80: "Al {pct} %",
      al100: "Límite alcanzado",
      de: "{usado} de {tope}",
      soporte: "Entradas nuestras en modo soporte",
      soporteAyuda: "Cada vez que el equipo técnico entra a mirar, en solo lectura, queda apuntado aquí.",
      soporteVacio: "No hemos entrado nunca.",
      pantallas: "{n} pantallas",
    },
  },
  tecnico: {
    coste: {
      titulo: "Coste y uso",
      costeMes: "Coste de IA este mes",
      preguntas: "Preguntas",
      materiales: "Material",
      interno: "Tareas internas",
      velocidad: "Tiempo hasta la primera letra",
      velocidadTexto: "{p90} s en 9 de cada 10 preguntas (mediana {p50} s)",
      errores: "Errores recientes",
      sinErrores: "Sin errores recientes.",
      correos: "Correos enviados este mes",
    },
    soporte: {
      titulo: "Modo soporte",
      subtitulo: "Ver la academia como la dirección, en solo lectura. Queda registrado y la dirección recibe un aviso.",
      entrar: "Entrar en modo soporte",
      registro: "Registro de entradas",
      noVe: "En modo soporte no se ven conversaciones, notas ni memoria de ningún alumno.",
    },
    limites: {
      titulo: "Límites y cuentas",
      academia: "Límites de la academia",
      alumno: "Límites de una persona",
      buscar: "Correo de la persona",
      preguntasDia: "Preguntas al día",
      materialesMes: "Materiales al mes",
      guardar: "Guardar",
      guardado: "Guardado.",
      baja: "Dar de baja la cuenta",
      noEncontrada: "No hay nadie con ese correo.",
      porDefecto: "Por defecto: {n}",
    },
  },

  entrar: {
    titulo: "Entra en tu asistente de estudio",
    texto: "Escribe tu correo y te mandamos un enlace para entrar. Sin contraseñas.",
    etiquetaCorreo: "Tu correo",
    ejemploCorreo: "lucia@correo.es",
    boton: "Enviarme el enlace",
    faltaArroba: "Falta la @. Revisa el correo y vuelve a probar.",
    correoMal: "Ese correo no parece bien escrito. Revísalo y vuelve a probar.",
    revisaTitulo: "Revisa tu correo",
    revisaTexto: "Si {correo} está dado de alta en {academia}, te hemos enviado un enlace para entrar. Caduca en una hora.",
    revisaPista: "¿No te llega? Mira en la carpeta de correo no deseado.",
    reenviar: "Reenviar el enlace",
    reenviarEn: "Podrás reenviarlo en {n} s",
    reenviado: "Enviado otra vez.",
    otroCorreo: "Usar otro correo",
    caducadoTitulo: "Este enlace ya no sirve",
    caducadoTexto: "Los enlaces para entrar caducan a la hora y solo sirven una vez. Pide uno nuevo.",
    pedirOtro: "Pedir un enlace nuevo",
    confirmarTitulo: "Ya casi estás",
    confirmarTexto: "Pulsa el botón para entrar en {academia}.",
    confirmarBoton: "Entrar",
    demasiados: "Has pedido muchos enlaces. Espera una hora y vuelve a probar.",
    salir: "Cerrar sesión",
  },

  papeles: {
    alumno: "Estudio",
    formador: "Formación",
    dueno: "Dirección",
    tecnico: "Técnico",
    selector: "Cambiar de parte",
  },

  menuAlumno: {
    preguntar: "Preguntar",
    crear: "Crear",
    biblioteca: "Biblioteca",
    repasar: "Repasar",
    progreso: "Progreso",
    conversaciones: "Mis conversaciones",
    loQueSe: "Lo que sé de ti",
    cuenta: "Mi cuenta",
    perfil: "Tu perfil",
  },

  menuGestion: {
    parteFormador: "Formación",
    temario: "Temario",
    alumnos: "Alumnos",
    material: "Material para clase",
    dudas: "Dudas",
    ayuda: "Ayuda",
    parteMetricas: "Métricas",
    uso: "Uso",
    dudasAtascos: "Dudas y atascos",
    riesgo: "Alumnos en riesgo",
    progresoGrupo: "Progreso del grupo",
    materialMetricas: "Material",
    parteAjustes: "Ajustes de la academia",
    equipo: "Equipo",
    grupos: "Oposiciones y grupos",
    consumo: "Consumo",
    parteTecnico: "Panel técnico",
    coste: "Coste y uso",
    soporte: "Modo soporte",
    limites: "Límites y cuentas",
    menu: "Menú",
  },

  soporte: {
    banda: "Modo soporte · solo lectura",
    salir: "Salir del modo soporte",
  },

  pausado: {
    titulo: "El servicio está pausado",
    texto: "Habla con tu academia para saber cuándo vuelve a estar disponible.",
  },

  error: {
    titulo: "Algo ha fallado",
    texto: "No es culpa tuya. Ya nos ha llegado el aviso. Vuelve a intentarlo o vuelve al inicio.",
    reintentar: "Volver a intentarlo",
    inicio: "Volver al inicio",
    caidoTitulo: "Estamos arreglando un problema",
    caidoTexto: "Vuelve en unos minutos.",
  },

  correos: {
    pie: "Este correo te lo envía {academia}. Si no esperabas recibirlo, puedes ignorarlo.",
    pieDesactivar: "Puedes desactivar este aviso en Mi cuenta.",
    enlace: {
      asunto: "Tu enlace para entrar en {academia}",
      titulo: "Tu enlace para entrar",
      texto: "Pulsa el botón para entrar en tu asistente de estudio. El enlace caduca en una hora y solo sirve una vez.",
      boton: "Entrar",
    },
    invitacion: {
      asunto: "{academia} te invita a su asistente de estudio",
      titulo: "Hola, {nombre}",
      texto: "{academia} te ha dado de alta en su asistente de estudio. {asistente} te resuelve las dudas del temario a cualquier hora, siempre con el tema y la página, y te ayuda a crear tu propio material.",
      boton: "Entrar ahora",
      nota: "Para entrar no necesitas contraseña: cada vez que quieras, escribe tu correo y te mandamos un enlace.",
    },
    invitacionDireccion: {
      asunto: "Tu asistente de estudio de {academia} está listo",
      titulo: "Hola, {nombre}",
      texto: "Ya puedes entrar en el asistente de estudio de {academia}. Desde tu parte verás las métricas de la academia, crearás los grupos e invitarás a tus formadores.",
      boton: "Entrar ahora",
    },
    invitacionFormador: {
      asunto: "{academia} te invita como formador",
      titulo: "Hola, {nombre}",
      texto: "{academia} te ha dado de alta como formador. Desde tu parte podrás subir el temario, invitar alumnos, contestar sus dudas y ver las métricas de tus grupos.",
      boton: "Entrar ahora",
    },
    bienvenida: {
      asunto: "Bienvenido a {academia}: tres consejos para empezar",
      titulo: "Tres consejos para empezar",
      consejo1: "Pregunta como se lo preguntarías a tu profesor. {asistente} te contesta con el tema y la página: pulsa la cita para leerla en el temario.",
      consejo2: "Crea tarjetas de repaso de lo que más te cueste y entra cada día en «Repasar hoy». Son cinco minutos.",
      consejo3: "Prueba el modo examinador: {asistente} te pregunta a ti y te corrige. Es la mejor forma de saber si te lo sabes.",
      boton: "Empezar a estudiar",
    },
    recordatorio: {
      asunto: "{asistente} te echa de menos",
      titulo: "{asistente} te echa de menos",
      texto: "Hace {dias} días que no entras. Un repaso de diez minutos hoy vale más que una tarde entera la semana que viene.",
      boton: "Volver a estudiar",
    },
    respuestaFormador: {
      asunto: "Tu formador ha contestado tu duda",
      titulo: "Tu formador ha contestado",
      texto: "Tienes la respuesta en tu conversación con {asistente}.",
      boton: "Ver la respuesta",
    },
    temarioProcesado: {
      asunto: "Temario listo: {tema}",
      titulo: "El temario ya está listo",
      texto: "{tema} ({paginas} páginas) ya está procesado. {asistente} ya lo usa para contestar.",
      textoError: "No hemos podido procesar {tema}: {motivo}",
      boton: "Ver el temario",
    },
    dudasPendientes: {
      asunto: "Tienes {n} dudas sin contestar",
      titulo: "Dudas pendientes en tu bandeja",
      texto: "Tus alumnos tienen {n} dudas esperando respuesta. No verás su nombre: solo la pregunta.",
      boton: "Abrir la bandeja",
    },
    resumenSemanal: {
      asunto: "Resumen de la semana en {academia}",
      titulo: "Tu resumen de la semana",
      activos: "Alumnos activos",
      preguntas: "Preguntas",
      materiales: "Materiales creados",
      riesgo: "Alumnos en riesgo",
      dudas: "Dudas más frecuentes",
      pocosDatos: "No hay suficientes alumnos para mostrar este dato sin identificar a nadie.",
      boton: "Ver las métricas",
    },
    cercaLimite: {
      asunto: "{academia} ha usado el {pct} % de su tope de {que} del mes",
      titulo: "Aviso de consumo",
      texto: "Este mes lleváis {usado} de {tope} {que}. Al llegar al 100 %, los alumnos no podrán hacer más hasta el mes que viene. Escríbenos si queréis ampliarlo.",
      boton: "Ver el consumo",
    },
    cuentaCompartida: {
      asunto: "Posible cuenta compartida en {academia}",
      titulo: "Posible cuenta compartida",
      texto: "La cuenta de {nombre} ({correo}) se está usando a la vez desde {n} sitios distintos: {ciudades}. Puede que la esté compartiendo.",
      boton: "Ver alumnos",
    },
    soporte: {
      asunto: "Hemos entrado en modo soporte en {academia}",
      titulo: "Hemos entrado en modo soporte",
      texto: "El equipo técnico ({tecnico}) ha entrado a mirar vuestra academia en modo solo lectura, el {fecha}. No puede cambiar nada ni ver conversaciones, notas ni memoria de ningún alumno. La entrada queda apuntada en Consumo.",
      boton: "Ver el registro",
    },
  },
};

export type Textos = typeof es;
